/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BagRouteImport } from './routes/bag'
import { Route as CapsRouteImport } from './routes/caps'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as GearRouteImport } from './routes/gear'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrintRouteImport } from './routes/print'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WallRouteImport } from './routes/wall'
import { Route as ProductSlugRouteImport } from './routes/product/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsRoute = CapsRouteImport.update({
  id: '/caps',
  path: '/caps',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/caps': typeof CapsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/gear': typeof GearRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/policies': typeof PoliciesRoute
  '/print': typeof PrintRoute
  '/shop': typeof ShopRoute
  '/wall': typeof WallRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/caps': typeof CapsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/gear': typeof GearRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/policies': typeof PoliciesRoute
  '/print': typeof PrintRoute
  '/shop': typeof ShopRoute
  '/wall': typeof WallRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bag': typeof BagRoute
  '/caps': typeof CapsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/gear': typeof GearRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/policies': typeof PoliciesRoute
  '/print': typeof PrintRoute
  '/shop': typeof ShopRoute
  '/wall': typeof WallRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bag'
    | '/caps'
    | '/cart'
    | '/checkout'
    | '/gear'
    | '/order-confirmed'
    | '/policies'
    | '/print'
    | '/shop'
    | '/wall'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bag'
    | '/caps'
    | '/cart'
    | '/checkout'
    | '/gear'
    | '/order-confirmed'
    | '/policies'
    | '/print'
    | '/shop'
    | '/wall'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/bag'
    | '/caps'
    | '/cart'
    | '/checkout'
    | '/gear'
    | '/order-confirmed'
    | '/policies'
    | '/print'
    | '/shop'
    | '/wall'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BagRoute: typeof BagRoute
  CapsRoute: typeof CapsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  GearRoute: typeof GearRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PoliciesRoute: typeof PoliciesRoute
  PrintRoute: typeof PrintRoute
  ShopRoute: typeof ShopRoute
  WallRoute: typeof WallRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caps': {
      id: '/caps'
      path: '/caps'
      fullPath: '/caps'
      preLoaderRoute: typeof CapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BagRoute: BagRoute,
  CapsRoute: CapsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  GearRoute: GearRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PoliciesRoute: PoliciesRoute,
  PrintRoute: PrintRoute,
  ShopRoute: ShopRoute,
  WallRoute: WallRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
